### ISSUE TITLE
Implement observability on garbage collection needs of failed Stack runs

### ISSUE THREAD

**Issue by metral** [pulumi/pulumi-kubernetes-operator#10]
In the scenarios that stacks can be stuck in a failure, resources in flight could be in a pending or failed state.
We should provide the information listed in the `pending_operations`.

- [ ] Log the resources orphaned in the update
- [ ] Reflect the log of orphaned resources in CR `spec.status` field

**Comment by rodcloutier** [comment]
Could the issue be a little more fleshed out? 
What type of resources are orphaned? 
Do you mean to implement garbage collection per say or just add observability on orphan resources?

**Comment by metral** [comment]
Thank you for your questions. We've updated the issue title and desc to better reflect the scope of this issue to be about informing the user of what operations are stuck in a pending state.

**Comment by lukehoban** [comment]
I don't believe there's any actual "garbage collection" we would do here.  I think this is just another part of what's tracked in https://github.com/pulumi/pulumi-kubernetes-operator/issues/9 - to expose potentially-leaked resources into the CR.  I'll add this as a bullet there to track in one place.
