### ISSUE TITLE
Changes in input do not trigger a stack update

### ISSUE THREAD

**Issue by rodcloutier** [pulumi/pulumi-kubernetes-operator#102]
### Problem description

Once a stack is created and at the desired state, changes to the input will not trigger a stack update. 
Only changes in the commit reference to the program will or deletion of the stack

### Reproducing the issue

Create a stack, update one of the input.
Observe: no reconciliation action

### Suggestions for a fix

Seem related to these lines of code: https://github.com/pulumi/pulumi-kubernetes-operator/blob/master/pkg/controller/stack/stack_controller.go#L218

**Comment by EvanBoyle** [comment]
@rodcloutier, can you provide more detail on what input you are changing? Is it some portion of the custom resource definition?
