### ISSUE TITLE
Github Actions failing due to use of set-env and get-path commands

### ISSUE THREAD

**Issue by viveklak** [pulumi/pulumi-kubernetes-operator#108]
### Problem description
Currently GHA workflows are failing due to use of `set-env` and `get-path` commands. See https://github.com/pulumi/pulumi-kubernetes-operator/pull/107/checks?check_run_id=1475352598 for an example.

**Comment by lukehoban** [comment]
Adding P1 as this is blocking all PRs in this repo currently.

**Comment by viveklak** [comment]
#110 should hopefully address this. Currently blocked verification due to GHA outage however.
