### ISSUE TITLE
Support for semVer expressions

### ISSUE THREAD

**Issue by rustrial** [pulumi/pulumi-kubernetes-operator#117]
Hi,

Being a long term Pulumi user, our SRE team recently started looking into the `pulumi-kubernetes-operator`, to make the power of Pulumi easily available to all our DevOps staff members. We are also using FluxCD (v2) with its very powerful and well designed [source-controller](https://github.com/fluxcd/source-controller), which makes is very easy to support GitOps driven workflows. 

Looking at the current state of the `pulumi-kubernetes-operator` project and its capabilities, the first thing that our engineers missed, is the capability to track [semVer tags expressions](https://github.com/Masterminds/semver) (e.g. `>= 1.0.0` or `>= 1.0.0-alpha0`), something which is actually well supported by the FluxCD `source-controller`.

Therefore, I am wondering whether you considered supporting (or maybe vendoring) [source-controller](https://github.com/fluxcd/source-controller) in `pulumi-kubernetes-operator` for the reconciliation of Git repositories. Combining the the power and versatility of Pulumi with the resilience and GitOps capabilities of `source-controller` could make `pulumi-kubernetes-operator` the one-stop solution for teams working on Kubernetes.

**Comment by EronWright** [comment]
Happy to report that the Pulumi Kubernetes Operator supports the use of Flux sources.
https://www.pulumi.com/blog/pulumi-kubernetes-new-2022/

With this you can leverage Flux's advanced tracking abilities with the Pulumi Operator. Enjoy!
