### ISSUE TITLE
Expose metrics

### ISSUE THREAD

**Issue by sfc-gh-jelsesiy** [pulumi/pulumi-kubernetes-operator#123]
To gain visibility into reconciliation latency, errors, usual resource metrics such as CPU, mem, fd usage etc. it would be good if the pulumi-operator would implement at minimum the controller-runtime default metrics, see [here](https://github.com/kubernetes-sigs/controller-runtime/blob/3645df01769a3f131a6d9adfe4dfd6f76206ff82/pkg/internal/controller/metrics/metrics.go).

**Comment by viveklak** [comment]
FWIW we do get the default metrics from the operator SDK and the endpoint is available at `0.0.0.0:8383` on the pod. Probably need to update the spec with the appropriate scraping annotations. If there is a standard set we should add - happy to take a contribution on this front.

**Comment by sfc-gh-mtreadwell** [comment]
Adding on to this, I think having some of the following metrics for stack info would be nice (for the endpoint on `0.0.0.0:8686`).
* Update duration
* Number of stacks currently updating/reconciling
* Number of stacks with last update failed
* Number of stacks
* Total number of updates (along with failures/success)
* Number of resources created/modified/deleted

**Comment by sfc-gh-mtreadwell** [comment]
@viveklak Are there any updates or plans to implement this on the Pulumi side?

**Comment by viveklak** [comment]
> @viveklak Are there any updates or plans to implement this on the Pulumi side?

This is on our prioritized backlog. The team is currently working towards some time-sensitive releases but we intend to have support for this by end of October. Thanks for your patience.
