### ISSUE TITLE
Operator switches back to pulumi console secret manager from cloud/custom on update 

### ISSUE THREAD

**Issue by viveklak** [pulumi/pulumi-kubernetes-operator#135]
When using a cloud secret manager, the initial update works correctly and the cloud secret manager (or passphrase) is used. However, at the next update, the secret manager is switched back to pulumi console.

## Expected behavior
The initial secret manager is retained on updates

## Current behavior
Always silently switches to pulumi api secret manager.
 
## Steps to reproduce

1. Create a stack with non-default secret manager, e.g. `"hashivault://my-key"` (see https://gist.github.com/viveklak/05344c9c684dce4dea41bb09915903e0#file-operatorwithvaultsecretmanager-md for instructions to use hashivault secret manager)
2. Deploy the stack and run `pulumi stack export -s <stack>` to check that the secret manager is set to cloud:
```
...
 "secrets_providers": {
            "type": "cloud",
            "state": {
                "url": "hashivault://my-key",
                "encryptedkey": "...."
            }
        },
...
```
3. Change something in the stack config or code to trigger an update
4. Run `pulumi stack export -s <stack>` to show that the secret manager is back to pulumi console:
```
"secrets_providers": {
            "type": "service",
            "state": {
                "url": "https://api.pulumi.com",
                "owner": "..",
                "project": "empty-stack",
                "stack": "..."
            }
        },
```

**Comment by EvanBoyle** [comment]
@viveklak are these examples helpful at all? https://github.com/pulumi/automation-api-examples/pull/25

I believe that you need to specify `StackSettings` (which I don't see anywhere in the operator) when you use a custom secrets provider.
