### ISSUE TITLE
Python examples of stacks creating don't work

### ISSUE THREAD

**Issue by jancespivo** [pulumi/pulumi-kubernetes-operator#161]
Python examples in https://github.com/pulumi/pulumi-kubernetes-operator/blob/master/docs/create-stacks-using-pulumi-python.md don't work because parameters in spec are "snake_cased". They work if parameters are "camelCased". Probably "feature" of the `apiextensions.CustomResource` :man_shrugging:

**Comment by lukehoban** [comment]
Thanks - looks like the example code is wrong here - and we should update it.  (PRs welcome :smile:)

**Comment by jancespivo** [comment]
Related PR https://github.com/pulumi/pulumi-kubernetes-operator/pull/163 ;)

**Comment by lukehoban** [comment]
Fixed with https://github.com/pulumi/pulumi-kubernetes-operator/pull/163.
