### ISSUE TITLE
Remove default "master" branch behavior

### ISSUE THREAD

**Issue by lblackstone** [pulumi/pulumi-kubernetes-operator#164]
I think we should change the operator to require that either a branch or commit is specified, and get rid of the default behavior of deploying the `master` branch. The user is already specifying other information about the git repo in the Stack CR, so it shouldn't be an undue burden to be explicit about the desired behavior. Furthermore, both the `git` CLI and GitHub have moved to using `main` as the default branch name, so using `master` is no longer a good default assumption.

## Affected feature

`Stack` CustomResource will currently deploy the latest commit from the `master` branch if neither `branch` nor `commit` is specified.

**Comment by elsesiy** [comment]
I agree that specifying either branch or commit via the stack CR is a reasonable expectation and is how I envisioned to use the polling feature. If anything, being explicit about which revision is tracked helps debug issues and prevent misconfigurations
