### ISSUE TITLE
Upgrading operator is not safe

### ISSUE THREAD

**Issue by elsesiy** [pulumi/pulumi-kubernetes-operator#171]
Upgrading the operator image to receive new features and bug fixes requires pod restarts. However, if there's an ongoing stack reconciliation this results in an unrecoverable error along the lines of:

`Concurrent stack update - No re-attempt`

## Steps to reproduce

1. Ensure there's a reconciliation running (check pulumi console)
2. Update pod image
3. Observe error

Expected: It should be safe to update the operator at any time and recover without manual pulumi operations.
Actual: Stack update fails & no re-attempt requiring manual user intervention.

**Comment by elsesiy** [comment]
cc @viveklak @lblackstone

**Comment by viveklak** [comment]
Thanks @elsesiy. I think this will require us to upgrade the controller runtime to pickup https://github.com/kubernetes-sigs/controller-runtime/commit/21a81bced73737f6bbc7c2a973d17c55c505e91c

**Comment by viveklak** [comment]
This will go out in v0.0.17 I am about to release. Note the upgrade *to* 0.0.17 will likely be unsafe as well. Its the subsequent updates we expect to be safe since the change here controls graceful shutdown of the reconciliation loop.

**Comment by elsesiy** [comment]
I just tested the latest version and unfortunately this issue still persists. Can we reopen it?

**Comment by viveklak** [comment]
I believe we are resorting to the default leader election timeout of 30 seconds. Will make this configurable and will need to tweak the deployment spec correspondingly.
