### ISSUE TITLE
Helm Chart Deployment fails

### ISSUE THREAD

**Issue by dirien** [pulumi/pulumi-kubernetes-operator#172]
I try to deploy a helm chart via the pulumi-k8s-operator. But the operator can not deploy it. 

## Steps to reproduce

1. Deploy the Operator
2. Define Stack with a helm chart init
3. Wait for the error message...

Expected:  Helm Chart gets deployed
Actual: Error Message:

```bash
dirien/aiven-openfaas/dev (pulumi:pulumi:Stack)
error: program failed: waiting for RPCs: failed to invoke helm template: rpc error: code = Unknown desc = invocation of kubernetes:helm:template returned an error: failed to generate YAML for specified Helm chart: failed to pull chart: looks like "https://openfaas.github.io/faas-netes/" is not a valid chart repository or cannot be reached: open /root/.cache/helm/repository/jhSyJ-Xs34gmamfZnSBpoFXwiqE=-index.yaml: permission denied

exit status 1
```

**Comment by clstokes** [comment]
@dirien can you share the pulumi code for the helm chart you're deploying?

**Comment by dirien** [comment]
HI @clstokes, yes of course -> https://github.com/dirien/pulumi-aiven-openfaas/tree/operator

In the `00-infrastructure`folder.  Tried it on a fresh k8s install again and still the same message.

**Comment by viveklak** [comment]
@dirien have you tried this on a recent operator release? I believe this was due to XDG_CACHE_HOME being routed to the /root directory which has been fixed in https://github.com/pulumi/pulumi-kubernetes-operator/pull/181

**Comment by viveklak** [comment]
You could also override this with the $HELM_CACHE_HOME environment variable. I will close for now but please reopen if the above doesn't fix for you.
