### ISSUE TITLE
Role is missing leases permission

### ISSUE THREAD

**Issue by jsravn** [pulumi/pulumi-kubernetes-operator#192]
```
E0903 12:44:52.523198       1 leaderelection.go:325] error retrieving resource lock pulumi-dev/pulumi-kubernetes-operator-lock: leases.coordination.k8s.io "pulumi-kubernetes-operator-lock" is forbidden: User "system:serviceaccount:pulumi-dev:pulumi-kubernetes-operator" cannot get resource "leases" in API group "coordination.k8s.io" in the namespace "pulumi-dev"
```

Using v0.0.19 of the operator, the logs are spammed with this error. Seems like the role just needs the lease permission.

**Comment by viveklak** [comment]
@jsravn Apologies. This is fixed in https://github.com/pulumi/pulumi-kubernetes-operator/pull/191
As a workaround please consider using the updated role definition in that PR.

**Comment by viveklak** [comment]
I have retagged 0.0.19 with the fix. Apologies for the inconvenience!

**Comment by jsravn** [comment]
Thanks!
