### ISSUE TITLE
Permalink Error Causes Self Hosted Backend To Not Refresh

### ISSUE THREAD

**Issue by boxboatjohn** [pulumi/pulumi-kubernetes-operator#193]
I'm trying to set up the operator with a self hosted s3 backend. However, logs are filled with this:

```
{"level":"error","ts":1631069404.0511198,"logger":"controller_stack","msg":"Failed to refresh stack","Request.Namespace":"default","Request.Name":"bbolt","Stack.Name":"bbolt","error":"failed to get permalink","errorVerbose":"failed to get permalink\ngithub.com/pulumi/pulumi/sdk/v3/go/auto.init\n\t/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.11.1-0.20210831183205-233b396f2923/go/auto/stack.go:682\nruntime.doInit\n\t/opt/hostedtoolcache/go/1.16.2/x64/src/runtime/proc.go:6265\nruntime.doInit\n\t/opt/hostedtoolcache/go/1.16.2/x64/src/runtime/proc.go:6242\nruntime.doInit\n\t/opt/hostedtoolcache/go/1.16.2/x64/src/runtime/proc.go:6242\nruntime.doInit\n\t/opt/hostedtoolcache/go/1.16.2/x64/src/runtime/proc.go:6242\nruntime.main\n\t/opt/hostedtoolcache/go/1.16.2/x64/src/runtime/proc.go:208\nruntime.goexit\n\t/opt/hostedtoolcache/go/1.16.2/x64/src/runtime/asm_amd64.s:1371","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.0/pkg/internal/controller/controller.go:298\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.0/pkg/internal/controller/controller.go:253\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.0/pkg/internal/controller/controller.go:214"}
```

## Steps to reproduce
1. Set stack with self hosted backend. 
2. Set stack to `refresh: true`
3. If resource changes outside of Pulumi, the stack is refreshed and updated in the object storage, but the `pulumi up` never happens. It refreshes the state, and then gives the above error and keeps looping over and over.

Expected: State to be refreshed and the operator then reruns the Pulumi program.
Actual: The stack is updated, but the Pulumi program is never run to reconcile the state. Then this happens all over again.

Without pulling the code down it looks like maybe this is the issue? https://github.com/pulumi/pulumi-kubernetes-operator/blob/d7f1737021d53d54c8e3abfb7ae806645a13c0da/pkg/controller/stack/stack_controller.go#L816

`sess.RefreshStack` calls `auto.GetPermalink` and doesn't take into account if the backend is self hosted and doesn't have a permalink and just returns an error.

**Comment by boxboatjohn** [comment]
Also, sorry didn't mention it. This is v0.0.19.

**Comment by boxboatjohn** [comment]
Looks like this issue was caught here:

https://github.com/pulumi/pulumi-kubernetes-operator/blob/d7f1737021d53d54c8e3abfb7ae806645a13c0da/pkg/controller/stack/stack_controller.go#L844-L847

**Comment by viveklak** [comment]
@boxboatjohn indeed the error is caught. I agree this can be spammy though. Did you try bumping the logging level to see what is causing the error? If there is an error causing the reconcile to fail you should see the status on the stack CR updated...

**Comment by boxboatjohn** [comment]
Right, it's returning an error but the error is that there isn't a permalink even though the self hosted backends don't have a permalink.

I opened #194 to I think fix this issue.

**Comment by viveklak** [comment]
Fixed in https://github.com/pulumi/pulumi-kubernetes-operator/pull/200.
