### ISSUE TITLE
Support Yarn (+ yarn workspaces) Explicitly

### ISSUE THREAD

**Issue by liamawhite** [pulumi/pulumi-kubernetes-operator#196]
Per discussion on Slack, the operator currently looks for [npm then falls back to yarn](https://github.com/pulumi/pulumi-kubernetes-operator/blob/master/pkg/controller/stack/stack_controller.go#L729). We can workaround by uninstalling npm in an init container.

We use yarn workspaces so can't rely on just looking for `yarn.lock` in the package root either as it only exists in the repo root.

**Comment by liamawhite** [comment]
Additionally, we also have to run as root.

```
{"level":"debug","ts":1632162989.3121283,"logger":"controller_stack","msg":"NPM/Yarn","Request.Namespace":"pulumi-operator","Request.Name":"...","Dir":"...","Path":"/usr/bin/yarn","Args":["/usr
/bin/yarn","install"],"Text":"Error: EACCES: permission denied, open '/tmp/.config/yarn'"}
```

**Comment by liamawhite** [comment]
For people who want a work around we use the following docker image:

```
FROM pulumi/pulumi-kubernetes-operator:v0.0.20

# Enable us to use yarn, see https://github.com/pulumi/pulumi-kubernetes-operator/issues/196
USER root
RUN npm uninstall npm -g

# We need write permissions for yarn, see https://github.com/pulumi/pulumi-kubernetes-operator/issues/196#issuecomment-923182126
RUN chown -R pulumi-kubernetes-operator:pulumi-kubernetes-operator /tmp
USER pulumi-kubernetes-operator
```

**Comment by EronWright** [comment]
Good news everyone, we just released a preview of Pulumi Kubernetes Operator v2. This new release has a whole-new architecture that uses pods as the execution environment. The installation procedure is handled with `pulumi install` and should work in all cases.

Please read the announcement blog post for more information:
https://www.pulumi.com/blog/pulumi-kubernetes-operator-2-0/

Would love to hear your feedback!  Feel free to engage with us on the #kubernetes channel of the [Pulumi Slack workspace](https://slack.pulumi.com/).
