### ISSUE TITLE
Migrate to kubebuilder based layout

### ISSUE THREAD

**Issue by viveklak** [pulumi/pulumi-kubernetes-operator#212]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details
We currently use deprecated versions of the operator-framework tooling to manage this repository. We should consider migrating to 1.0.0+ supported tooling by following the migration guide here:

https://sdk.operatorframework.io/docs/building-operators/golang/migration/

This should also facilitate supporting features like #124 more easily and will make it simpler to support #123 by being more user-friendly.

**Comment by EronWright** [comment]
This was done for v2.
