### ISSUE TITLE
Periodic re-sync for stacks

### ISSUE THREAD

**Issue by sfc-gh-jelsesiy** [pulumi/pulumi-kubernetes-operator#242]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Pulumi operator reconciles based on changes to git revisions in the tracking repo. However, there are use cases where the pulumi program in the repo has some dynamic element to it such as making an API call to some upstream system to determine the resource to be created. An example of that could be talking to the GitHub Meta API to obtain IPs to be allowlisted on a security group. In today's world, this would require one to make a dummy commit to the repo before the operator would pick up the change.

To alleviate these issues, pulumi operator should support periodic re-sync of stacks regardless whether the commit sha in the tracking repo changed or not.

**Comment by viveklak** [comment]
We could store a last resync timestamp in status and expose a resync frequency in the stack to allow specifying how often resyncs ought to happen. For successful resyncs the reconciler can set the timestamp and then trigger a resync if the desired time has elapsed
