### ISSUE TITLE
Consider caching polled git repositories

### ISSUE THREAD

**Issue by viveklak** [pulumi/pulumi-kubernetes-operator#244]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details
With the addition of branch polling in #162 and periodic resyncs in #242, the operator will often checkout repos at the same revision. There is a slight concern on overhead being imposed because of this internally as well as to the source control provider. We should consider adding a simple cache around polled git repositories. This may allow us to drop restrictions around resync intervals (currently min is 60 seconds).

**Comment by ghostsquad** [comment]
I highly agree with this. ArgoCD does this, and I'm looking to use Pulumi as a replacement to ArgoCD.

**Comment by EronWright** [comment]
Good news everyone, we just released a preview of Pulumi Kubernetes Operator v2. This new release has a whole-new architecture that uses pods as the execution environment, uses a more efficient approach to polling (akin to `git ls-remote --heads`), and retains the pod over time to serve as a cache. Also, we do support Flux as a source, and it caches repository content.

Please read the announcement blog post for more information:
https://www.pulumi.com/blog/pulumi-kubernetes-operator-2-0/

Would love to hear your feedback!  Feel free to engage with us on the #kubernetes channel of the [Pulumi Slack workspace](https://slack.pulumi.com/). 
cc @viveklak @ghostsquad @diablo39
