### ISSUE TITLE
Add "in-progress" to status

### ISSUE THREAD

**Issue by liamawhite** [pulumi/pulumi-kubernetes-operator#275]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

As discussed on Slack, we're polling the status of the CR until it's ready. Our logic for deciding if ready is does spec.commit === lastSuccessfulCommit. This works unless we have `continueResyncOnCommitMatch` set to true. In that situation, we can't know if there is an update in progress.

### Affected area/feature

The stack CR status field in the operator.

**Comment by guineveresaenger** [comment]
I'm going to cc @viveklak and @lblackstone here for input.

**Comment by squaremo** [comment]
After #316 (not in a release just yet), you can judge the "in progress" status by looking at the status condition with the name `Reconciling`: it will be present and set to `True` if the controller is processing that object.

There are two situations where this can be the case: 1. the controller is running the stack; or 2. the controller encountered some presumed transient problem with running the stack, abandoned that attempt, and queued it to tried again. There's a fair few things that can go wrong, but might come right at the next retry, so 2.) is expected from time to time. (E.g., in https://github.com/pulumi/pulumi-kubernetes-operator/blob/master/pkg/controller/stack/stack_controller.go#L261, Pulumi couldn't set up the project in a working directory -- but it might succeed next time, who knows)
