### ISSUE TITLE
Support drift detection and status check

### ISSUE THREAD

**Issue by kostis-codefresh** [pulumi/pulumi-kubernetes-operator#281]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

After initial creation of a stack the operator should work both ways. It should detect changes in Git and re-apply/update the stack but also check if somebody changes the stack manually via kubectl and or Pulumi CLI/GUI.

If this capability is implemented then the operator can be easily coupled with Flux/ArgoCD and get automatic drift detection and reconciliation (both ways).

## Scenario

1. I installed the Kubernetes operator on a cluster
1. I created a stack via kubectl -f (using the nginx stack sample)
1. The stack was correctly applied
1. Then I deleted manually the stack from the Pulumi CLI along with its resources
1. The operator did not detect the deletion

![delete](https://user-images.githubusercontent.com/39800303/171216297-3f61af76-2156-4b62-b569-e6cd3754a66d.png)
![stack-is-still-there](https://user-images.githubusercontent.com/39800303/171216318-dff64f74-c4df-4282-9e7f-7841f937cbb9.png)

### Observed behavior
Deleting manually a stack is not detected by the operator. So it seems that the operator is unidirectional (it only monitors Git and updates stacks and not the other way around)

### Expected behavior 
The operator should understand that the stack no longer exists and do something about it. At the very least it should emit an event OR change a status/state field to false OR automatically re-apply the stack again from Git

Disclaimer: I am a contributor to the Argo project. Implementing this feature could bring pulumi on par with Crossplane (and the terraform operator) for GitOps workflows. It seems that currently the pulumi operator is missing the last principle of https://opengitops.dev/

**Comment by rawkode** [comment]
For drift detection / constant reconciliation, you need two settings on your stack:

```
continueResyncOnCommitMatch: true
resyncFrequencySeconds: 60
```

**Comment by stack72** [comment]
Hi @kostis-codefresh 

My apologies that you are running into this issue - as @rawkode posted above, if you set those values on your stack then that should unblock you.

As a follow up here, @rawkode has kindly created https://github.com/pulumi/pulumi-kubernetes-operator/issues/283 as a discussion that we need to have to ensure better defaults in the operator.

I am going to close this specific issue out as the settings above will fix your specific problem here. We will track all further work in #283 and ensure this is updated and working as expected so that other users don't hit the same problem

I really appreciate the feedback here

Paul

**Comment by kostis-codefresh** [comment]
Hey @stack72 

I haven't check those settings yet, but I believe that if I apply them (and judging by their name) this will only fix the auto-sync issue.
Another aspect is how the operator detects that a change indeed happened externally and what is presented in the user. 

So yes, feel free to close this (and I will verify this myself as well), but indeed a bigger discussion is needed regarding the expectations of a GitOps operator.

**Comment by rawkode** [comment]
@kostis-codefresh Also use `refresh: true` to reconcile external changes. This is also mentioned in #283, but I forgot it above :)
