### ISSUE TITLE
Allow for aws:skipMetadataApiCheck

### ISSUE THREAD

**Issue by poobah** [pulumi/pulumi-kubernetes-operator#291]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

If you would like to use IAM creds for the Operator rather than pass AWS creds around it seems the Operator is running into this issue https://github.com/pulumi/pulumi-aws/issues/1692

Setting the AWS_EC2_METADATA_DISABLED does not appear to not work (as stated in the issue) 
 however adding aws:skipMetadataApiCheck to your provider works.

Might be worth adding this point your documentation as the examples all use AWS creds in the examples.

**Comment by poobah** [comment]
You can ignore

**Comment by poobah** [comment]
Hi @stack72,

Looks like the EnvVar does not work in pulumi-asp so no point yet in setting it but the provider setting does work. I suggested that the docs could do with stating that it is set in the provider (maybe adding to troubleshooting) if folks want to use IAM roles over AWS creds.

**Comment by EronWright** [comment]
This is fixed (thanks @t0yv0!) by https://github.com/pulumi/pulumi-aws/pull/3960.
