### ISSUE TITLE
Cannot use CodeCommit repositories due to go-git bug

### ISSUE THREAD

**Issue by pentikos** [pulumi/pulumi-kubernetes-operator#302]
### What happened?

When you specify a CodeCommit repository, the operator will fail with the error 
`failed to create local workspace: failed to create workspace, unable to enlist in git repo: unable to clone repo: reference delta not found`

### Steps to reproduce

Use a CommitCommit repository as source

### Expected Behavior

That it works :-)

### Actual Behavior

Throwing error `failed to create local workspace: failed to create workspace, unable to enlist in git repo: unable to clone repo: reference delta not found`

### Additional context

Some Googling led me to https://github.com/fluxcd/flux2/discussions/948
Either the solution is to switch to a different Git provider or wait until go-git has been fixed.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by viveklak** [comment]
Thanks for opening the issue @donpinkster. Yes we have seen this class of problems before. We are considering integrating with flux for source tracking which would allow us to leverage support in flux for such repositories. See https://github.com/pulumi/pulumi-kubernetes-operator/issues/158

**Comment by EronWright** [comment]
I believe this is fixed, and we now support Flux sources as was discussed.
