### ISSUE TITLE
Cannot use different ports in the projectRepo URL

### ISSUE THREAD

**Issue by donpinkster** [pulumi/pulumi-kubernetes-operator#304]
### What happened?

When you specify a port in the projectRepo URL it is not parsed correctly. I narrowed it down to the `giturls.Parse` method which eventually replaces `git@foobar.com:7999/foobar.git` with `git@foobar.com/7999/foobar.git`

### Steps to reproduce

Use a port in your projectRepo URL `git@foobar.com:7999/foobar.git`

### Expected Behavior

That the keyscan application can connect to the host and amend the known_hosts file

### Actual Behavior

It will fail silently

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by squaremo** [comment]
According to https://git-scm.com/docs/git-clone#_git_urls, `git@foobar.com:7999/foobar.git` means use SSH with the host `foobar.com` and the path `7999/foobar.git`. If you need to include a port, try `ssh://foobar.com:7999/foobar.git`.

**Comment by mikhailshilkov** [comment]
Since we haven't heard back, I'll go ahead and close this issue as stale. Please open a new issue if you still think there is a bug here. Thank you!
