### ISSUE TITLE
Design for operator bootstrap

### ISSUE THREAD

**Issue by squaremo** [pulumi/pulumi-kubernetes-operator#313]
Usually a Kubernetes operator will be packaged as a Helm chart or similar, with the circumstances of its deployment left to the user. The Pulumi operator is in a rare position of being able to define not only its own deployment, but the deployment of the cluster it runs in (or will run in) and layers underneath. This creates a knot for users who want to have "Pulumis all the way down" -- how do you bootstrap a system which applies (at least some of) its own definition?

**Comparison with Flux**

Flux has to solve a similar problem: it advocates for defining everything in the cluster as files in git to be synced, and that includes the Flux runtime. It does so by having a subcommand for its CLI -- `flux bootstrap` -- which ensures that

 1. there is a git repository with definitions for the Flux runtime
 2. there are definitions telling Flux to sync the git repo, in the git repo
 3. the definitions in 1) and 2) are applied to the cluster, to kick things off.

Some differences:

 - There's no CLI attached to the Pulumi operator, so no opportunity for a bootstrap subcommand; the nearest equivalent would be an formula for invoking `pulumi`, or a `helm install`
 - Flux can assume there's a Kubernetes cluster; but since Pulumi can define the underlying infrastructure, it's natural to write a Pulumi program that defines both the infrastructure _and_ the operator deployment (and everything sitting on top); the problem becomes one of eliding between modes of running that program.

**Comment by EronWright** [comment]
As of v2.0, we offer a few installation options:
1. A Pulumi program to deploy the operator in a totally managed way 
2. A Helm chart
3. A "quickstart" manifest file

I believe this covers the bootstrap requirement.
