### ISSUE TITLE
operator release with go 1.18

### ISSUE THREAD

**Issue by intrand** [pulumi/pulumi-kubernetes-operator#317]
### What happened?

We've updated our go dependencies and they now require go 1.18. The latest operator release does not include #298 which adds go 1.18 to the image. As well, the last operator release was back in early June. Without a new release, we cannot use the operator.

What is the timeline for creating a new release? Is it reasonable to create one sooner to allow the operator to function again for people who are compatible with the standalone binary?

### Steps to reproduce

Try running code requiring go 1.18 with the latest operator release.

### Expected Behavior

Once the standalone binary gets updated, I'd expect a corresponding operator release which includes it.

### Actual Behavior

The operator has a totally different release cadence than the standalone binary. This means I could test something at my desk (without kubernetes) and get a totally different, incompatible result when I go to deploy using our test environment (uses operator).

### Output of `pulumi about`

n/a

### Additional context

n/a

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by stack72** [comment]
Hi @intrand 

My apologies here - we will get a release of the operator made with this new version!

Paul

**Comment by intrand** [comment]
No need to apologize. Thanks very much for responding and getting a plan together. I'm interested in the current release cycle cadence. Are there currently any guidelines for making a new release, or is it just as-needed? We're wondering if we can anticipate releases or not.

Thanks again

**Comment by stack72** [comment]
@intrand 

great question! We will align our releases with the release of Pulumi CLI / SDK - that way the latest version is always going out. If there's a regression / urgent fix, we can be much more a-hoc

**Comment by intrand** [comment]
Thanks again @stack72 :D That sounds great to me! Looking forward to handing over most of the work the operator :)

**Comment by stack72** [comment]
Closed out as this was released :)
