### ISSUE TITLE
Use envtest to parallelize tests by giving each test its own etcd & kube-apiserver to use

### ISSUE THREAD

**Issue by metral** [pulumi/pulumi-kubernetes-operator#33]
The operator-sdk supports [`MaxConcurrentReconcilations`](https://github.com/operator-framework/operator-sdk/issues/3585), which is the number of workers a given operator can spawn to handle reconciliation loops. By default this is set to 1, but we set it to 10 (an arbitrary value greater than the default).

While this handles concurrency within a single operator to work with the APIserver, it *does not* handle concurrency across multiple instances/replicas of an operator. This means competing operators will fight to process the same Stack CRs, and causes concurrency issues that ultimately lead to extraneous reconciliation loops, and indeterministic stack update sequences.

The operator will need to be configured with [leader election](https://docs.openshift.com/container-platform/4.5/operators/operator_sdk/osdk-leader-election.html) to settle contention between multiple Operator instances by using an active-passive setup.

Related: https://github.com/operator-framework/operator-sdk/issues/3585

**Comment by metral** [comment]
Leader election is actually enabled by default within clusters thanks to the [operator-sdk](https://docs.openshift.com/container-platform/4.1/applications/operator_sdk/osdk-leader-election.html).

This issue is w.r.t running concurrent controller binaries in the test suite if using [`ginkgo -p`](https://onsi.github.io/ginkgo#parallel-specs), which run the controllers locally on the client, yet the controllers must connect to a k8s cluster to work with the API. In testing, we currently stand up an ephemeral GKE cluster and share that amongst tests.

When controllers run like this connected to the same cluster but the binaries don't actually run in-cluster, leader election can't help contentious competes.

The long term solution is to not share a cluster amongst the controller binaries if using test parallelism, and instead configure each test with its own ephemeral [envtest](https://godoc.org/sigs.k8s.io/controller-runtime/pkg/envtest) to simulate the API with a per-test, isolated etcd & kube-apiserver instance.

**Comment by infa-nang** [comment]
Hi, any ETA on when this will be fixed?

We have currently deployed single replica Pulumi Operator in our dev env, which currently manages 10 stacks and it consumes around 8-10Gb memory and 1-2cpus.

In production we might need to manage around 20-30 stacks, so it would be helpful if we can deploy multi replica Pulumi operator, so that each instance will run on a separate node with sufficient resources instead of needing a single beefy node

**Comment by EronWright** [comment]
Good news everyone, we just released a preview of Pulumi Kubernetes Operator v2. This new release has a whole-new architecture that uses pods as the execution environment. The scalability issue mentioned by @infa-nang has been addressed. Also, the `MaxConcurrentReconcilations` parameter was tuned for each controller.

Please read the announcement blog post for more information:
https://www.pulumi.com/blog/pulumi-kubernetes-operator-2-0/

Would love to hear your feedback!  Feel free to engage with us on the #kubernetes channel of the [Pulumi Slack workspace](https://slack.pulumi.com/). 
cc @JonCholas @davide-romanini-milkman @kerruba-milkman
