### ISSUE TITLE
Automate bump of image used in deployment programs

### ISSUE THREAD

**Issue by squaremo** [pulumi/pulumi-kubernetes-operator#334]
The programs under deploy/ all mention a specific version of the operator. At present these get edited by hand when there's a release, but they could be automated, e.g., by putting the version as an item of config and updating the config files.

**Comment by EronWright** [comment]
The strategy that was implemented for v2 is a make target that edits all known version infos throughout the codebase, such that the current version (`CURRENT_RELEASE` variable) becomes the new version (`RELEASE` variable). It is not invoked by CI, is invoked manually before tagging.
