### ISSUE TITLE
Overhaul logging

### ISSUE THREAD

**Issue by squaremo** [pulumi/pulumi-kubernetes-operator#354]
The logging is inconsistent (which makes it difficult to eyeball, and to use for any automation); and, not always very purposeful.

Ongoing wishlist:
- [x] There are duplicate labels, e.g., "namespace" is supplied when it's already been set on the reqLogger
- [x] The default level in configs should be info, rather than error -- people get confused when they run it and see no logs (because nothing bad is happening)
 - [x] The use of labels is inconsistent, both in which labels are used, and how they are spelt (especially with respect to case)
 - [x] The position and content of log messages should be audited -- does each log message tell the user something useful?

**Comment by dirien** [comment]
Some additional infos to log from a customer feedback:

- [ ] When a new run starts

- [ ] When a reconcile check happens and its result
