### ISSUE TITLE
Cannot set PULUMI_CONFIG_PASSPHRASE(_FILE) in `.Envs` or `.SecretEnvs`

### ISSUE THREAD

**Issue by squaremo** [pulumi/pulumi-kubernetes-operator#370]
The spec fields `.envs` and `.secretEnvs` are deprecated in favour of `.envRefs`, but are still expected to work -- the test case ["can deploy a stack with a file config"](https://github.com/pulumi/pulumi-kubernetes-operator/blob/56a8f592f393ce3334337483d6cf153ccc4f921a/test/stack_controller_test.go#L163) explicitly uses `.secretEnvs` to provide the secret. However, they are applied to the workspace _after_ the stack has been created, so the passphrase is not available to the stack state backend on initialisation, leading to errors in the log:

```
error: passphrase must be set with PULUMI_CONFIG_PASSPHRASE or PULUMI_CONFIG_PASSPHRASE_FILE environment variables
```

Weirdly, this doesn't cause the test to fail, even though (you would think) it would stop the controller getting any further. The controller succeeds the second time around, which makes me think there's a deeper problem with how stack initialisation works.

In any case: .envs and .secretEnvs should be set at the same time the .envRefs are processed, before the stack is created.

**Comment by EronWright** [comment]
Good news everyone, we just released a preview of Pulumi Kubernetes Operator v2. This new release has a whole-new architecture that uses pods as the execution environment. The environment variables are now attached to the pod before any stack operations occur.

Please read the announcement blog post for more information:
https://www.pulumi.com/blog/pulumi-kubernetes-operator-2-0/

Would love to hear your feedback!  Feel free to engage with us on the #kubernetes channel of the [Pulumi Slack workspace](https://slack.pulumi.com/). 
cc @squaremo
