### ISSUE TITLE
add output of `pulumi up` to the log of operator

### ISSUE THREAD

**Issue by zelig81** [pulumi/pulumi-kubernetes-operator#372]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

When Pulumi operator reconciles a stack - there is no output in log. If that can be switched on/off - it can be helpful for understanding of made changes and troubleshooting

### Affected area/feature

- add in Pulumi operator an output of `pulumi up` command (or `pulumi preview --diff`)

**Comment by thomas11** [comment]
Thank you for the suggestion, @zelig81! it makes sense and we'll queue it up.

**Comment by zelig81** [comment]
Thank you @thomas11

**Comment by dirien** [comment]
Adding feedback from another customer to this issue:

It would be nice to have these infos in the `info` level logs.

**Comment by EronWright** [comment]
Good news everyone, we just released a preview of Pulumi Kubernetes Operator v2. This new release has a whole-new architecture that uses pods as the execution environment. The logs from `pulumi up` are available as ordinary pod logs.

Please read the announcement blog post for more information:
https://www.pulumi.com/blog/pulumi-kubernetes-operator-2-0/

Would love to hear your feedback!  Feel free to engage with us on the #kubernetes channel of the [Pulumi Slack workspace](https://slack.pulumi.com/). 
cc @zelig81 @sfc-gh-jsirak
