### ISSUE TITLE
Update `Stack` columns with `Last Run Time`

### ISSUE THREAD

**Issue by rawkode** [pulumi/pulumi-kubernetes-operator#393]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

When running `kubectl get stacks`, it would be handy to know when the last run was so we can anticipate when the next might happen

**Comment by cleverguy25** [comment]
Added to epic https://github.com/pulumi/pulumi-kubernetes-operator/issues/586
