### ISSUE TITLE
Rework stack_controller_test.go to test mechanisms in isolation

### ISSUE THREAD

**Issue by squaremo** [pulumi/pulumi-kubernetes-operator#394]
stack_controller_test.go has tests of specific mechanisms (e.g., using a config that comes in a file with the program) along with smoke tests that run an example AWS-based stack using various means of providing config, secrets, etc.

There are two things to improve here:

 - don't rely on the AWS provider -- that doesn't really test anything other than that `pulumi` works as expected -- so the tests don't need AWS credentials, and complete faster
 - separate out each mechanism into its own test, so that failures are easier to diagnose

**Comment by EronWright** [comment]
The integration tests were completely re-designed and I think this goal was achieved.
