### ISSUE TITLE
Force a re-run even when there is no change in the git repository

### ISSUE THREAD

**Issue by dirien** [pulumi/pulumi-kubernetes-operator#398]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Feedback from on of our customers:

> It would be great if we can have a documented and reliable way to force a pulumi run even when a git change has not be made.

Customer is implementing currently `continueResyncOnCommitMatch` but would still love to see this feature in the future.

**Comment by EronWright** [comment]
My understanding of this enhancement request is to provide a manual re-sync trigger, i.e. `pulumi up` on demand.   Good news is that the `pulumi.com/reconciliation-request` annotation is [understood](https://github.com/pulumi/pulumi-kubernetes-operator/issues/672#issuecomment-2364665802) to have the semantic that it forced a re-sync, and was re-implemented in https://github.com/pulumi/pulumi-kubernetes-operator/pull/745.
