### ISSUE TITLE
Use of SSH host keys vulnerable to "man-in-the-middle" attacks

### ISSUE THREAD

**Issue by squaremo** [pulumi/pulumi-kubernetes-operator#406]
For git cloning using SSH, the operator uses strict host key checking (by not changing the default). This is great, because it means it won't establish connections to hosts for which it doesn't trust the host key, which helps defeat "man in the middle" (MitM) attacks.
However -- a big however -- it also uses `ssh-keyscan` to get host keys on the fly, when SSH is in use. This is not great -- it opens the door back up to MitM attacks. From [`man ssh-keyscan`](https://linux.die.net/man/1/ssh-keyscan):

> If an ssh_known_hosts file is constructed using ssh-keyscan without verifying the keys, users will be vulnerable to man in the middle attacks.

The solution used by Flux is to bake a known_hosts with all well-known git platforms into the Docker image, and to tell people how to create and install their own `known_hosts` file (e.g., by mounting it from a secret).

**Comment by blampe** [comment]
v2 of the operator no longer uses `ssh-keyscan`.

> The solution used by Flux is to bake a known_hosts with all well-known git platforms into the Docker image

We recommend doing the same. The base Pulumi image can be extended with `~/.ssh/known_hosts` populated, and the workspace's image can be customized by using the Stack's `.spec.workspaceTemplate.spec.image` field.
