### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by skdltmxn** [pulumi/pulumi-kubernetes-operator#420]
### What happened?

I see the memory consumption by the operator keeps increasing.  
Attached capture shows memory usage graph for past week.  
Considering there was no change for last four days, I don't understand why it's increasing.  
Could there be any memory leak?

<img width="1236" alt="image" src="https://user-images.githubusercontent.com/4114833/223000752-93949356-1a02-4072-9b98-b2235c0d9b28.png">

### Expected Behavior

The memory consumption should stay consistent unless there is any reason.

### Steps to reproduce

Run the operator with periodic reconcile enabled

### Output of `pulumi about`

```
CLI
Version      3.46.0
Go Version   go1.19.2
Go Compiler  gc

Host
OS       debian
Version  11.5
Arch     x86_64

Pulumi locates its logs in /tmp by default
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by danielrbradley** [comment]
Thanks for reporting this @skdltmxn 

This looks like it'll likely be a tricky issue to reproduce, can you share any more details about your setup (code if possible). Have you managed to reproduce the issue in a smaller isolated environment?

**Comment by skdltmxn** [comment]
Hi, I've been monitoring memory usage since this report, and further graph seems pretty stable.

Let me close the issue for now and open again if I could really assure myself there's some problems.

**Comment by danielrbradley** [comment]
This also might have been resolved by https://github.com/pulumi/pulumi-kubernetes-operator/pull/407 which was related to a cache growth issue. The next release that goes out will include this. Do let us know if you continue to see issues after upgrading.
