### ISSUE TITLE
Pulumi version is too old and doesn't work with project-scoped stacks

### ISSUE THREAD

**Issue by JonCholas** [pulumi/pulumi-kubernetes-operator#432]
### What happened?

We upgrade our pulumi backend to use project-scope stacks. Our pulumi operator stop working because the version in the docker image has pulumi 3.57.1

### Expected Behavior

A new version release of pulumi operator each time there is a release of pulumi

### Steps to reproduce

Use pulumi operator latest version (1.11.2) with any backend non-pulumi-service with project-scopeds stacks enabled

### Output of `pulumi about`

(this is the pulumi about inside the container running pulumi-operator)
root@beta-pulumi-operator-426fb36c-664b748464-27hpw:/# pulumi about
CLI          
Version      3.57.1
Go Version   go1.20.1
Go Compiler  gc

Host     
OS       debian
Version  11.6
Arch     x86_64

Pulumi locates its logs in /tmp by default

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mikhailshilkov** [comment]
@JonCholas Thank you for opening this issue! I created https://github.com/pulumi/pulumi-kubernetes-operator/pull/433 and will cut a new release after it's merged.

**Comment by JonCholas** [comment]
amazing, thanks @mikhailshilkov . Any chance to automate this in a pipeline? new version of pulumi triggering a new version of pulumi-operator or even introduce some envvar and a `start.sh` inside the container to set the pulumi to a given version
