### ISSUE TITLE
Custom images

### ISSUE THREAD

**Issue by mnlumi** [pulumi/pulumi-kubernetes-operator#451]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

The size of the kubernetes-operator container is currently [over 1GB compressed ](https://hub.docker.com/r/pulumi/pulumi-kubernetes-operator/tags) and 4.64GB uncompressed. It currently contains all available runtimes. It would be beneficial to publish multiple containers that are smaller in size and only contain the desired runtime.

**Comment by cleverguy25** [comment]
Added to epic https://github.com/pulumi/pulumi-kubernetes-operator/issues/586

**Comment by EronWright** [comment]
Good news everyone, we just release a preview of Pulumi Kubernetes Operator v2. This new release has a whole-new architecture that uses pods as the execution environment, and each stack may use a separate image. 
We do still use the "kitchen-sink" pulumi/pulumi image by default, but it is possible to use the language-specific images to optimize the pull. It is also now possible to customize a stack's image, e.g. to preinstall dependencies.

Please read the announcement blog post for more information:
https://www.pulumi.com/blog/pulumi-kubernetes-operator-2-0/

Would love to hear your feedback!  Feel free to engage with us on the #kubernetes channel of the [Pulumi Slack workspace](https://slack.pulumi.com/). 
cc @mnlumi @JonCholas @diablo39 @rodolfototaro @UnstoppableMango

**Comment by JonCholas** [comment]
@EronWright do we have ETA to move from beta to GA? I can't consider it fixed until I have a stable version I can put in production, we use pulumi-operator to provide "deployment" services to our customers (devs)
