### ISSUE TITLE
Implement a way to trigger a reconcile

### ISSUE THREAD

**Issue by jaxxstorm** [pulumi/pulumi-kubernetes-operator#455]
There are circumstances whereby you don't want to wait for the operator reconcile loop to do it's thing.

If you need to provision infrastructure "right now" and you're in a backoff loop, having a way to trigger a reconcile manually seems like a good addition. 

I've seen this implemented in other operators by hitting an endpoint with curl, for example

**Comment by rquitales** [comment]
Thanks for submitting this enhancement request as there are some scenarios where this could be useful.

This should already be supported as v1.12.0 of the operator introduces the `pulumi.com/reconciliation-request` annotation. To manually re-trigger the reconcile of a Stack CR, you should be able to update the value of that annotation to a new unique value. This will cause a reconcile, and upon success, the value of this annotation is then stored in the `.status.observedReconcileRequest` field so you can check the status to see whether the annotation has been seen by the controller (similar to `.status.observedGeneration`).


Thank you for submitting this enhancement request. It appears that your desired functionality is already available.

Starting from version 1.12.0 of the operator, a new annotation called `pulumi.com/reconciliation-request` has been introduced. By updating the value of this annotation to a unique value, you can manually trigger the reconciliation of a Stack CR. Subsequently, the controller will store the value of this annotation in the `.status.observedReconcileRequest` field. Similar to the `.status.observedGeneration` field, you can monitor the status to determine if the controller has detected the updated annotation. This approach eliminates the need for an external HTTP server and provides a KRM-friendly method to initiate a manual reconcile.

Example:
```
NEW_VALUE=$(uuidgen)
kubectl annotate stack <stack-name> pulumi.com/reconciliation-request="$NEW_VALUE" --overwrite
```
