### ISSUE TITLE
Reduce the frequency at which the Pulumi Operator hits the GitHub API

### ISSUE THREAD

**Issue by meagancojocar** [pulumi/pulumi-kubernetes-operator#461]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Posting on behalf of a customer. Mainly, this is to rate-limit API requests due to low API key limits.

This is partially addressed with ResyncFrequencySeconds; however, that does not impact (failures during deployment)[https://github.com/pulumi/pulumi-kubernetes-operator/blob/da76f15514ec9e7d99c885ddab019c3026e1d7dd/pkg/controller/stack/stack_controller.go#L872-L898], which result in requeue after a fixed interval of 5s or immediate requeue.

**Comment by kpitzen** [comment]
Thanks, @meagancojocar - we'll get this lined up as soon as we can.

**Comment by cleverguy25** [comment]
Added to epic https://github.com/pulumi/pulumi-kubernetes-operator/issues/586

**Comment by EronWright** [comment]
Good news everyone, we just released a preview of Pulumi Kubernetes Operator v2. This new release implements a back-off strategy when hitting upon stack errors, to avoid hitting the GH API too frequently:
https://github.com/pulumi/pulumi-kubernetes-operator/pull/709

Please read the announcement blog post for more information:
https://www.pulumi.com/blog/pulumi-kubernetes-operator-2-0/

Would love to hear your feedback!  Feel free to engage with us on the #kubernetes channel of the [Pulumi Slack workspace](https://slack.pulumi.com/).
