### ISSUE TITLE
Support additional authentication methods such as OAuth 2.0 Device Authorization Grants

### ISSUE THREAD

**Issue by meagancojocar** [pulumi/pulumi-kubernetes-operator#462]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Opened on behalf of a customer. Their ask is to support additional authentication methods such as OAuth 2.0 Device Authorization Grants. Community PRs welcome!

**Comment by kpitzen** [comment]
Hey @meagancojocar - thanks for opening this issue. Would love a complete list of authentication methods being requested, so we can gauge scope here. Thanks!

**Comment by EronWright** [comment]
I take this issue to be about authentication support for state backend.

Closing in favor of OIDC support:
https://github.com/pulumi/pulumi-kubernetes-operator/issues/697
