### ISSUE TITLE
Add kustomize support for deploying pulumi kubernetes operator

### ISSUE THREAD

**Issue by usrbinkat** [pulumi/pulumi-kubernetes-operator#473]
## Problem:

Operator install experience is not optimal. Kubectl install instructions link directly to README.md and instruct user to clone repo, cd to dir, and execute multiple kubectl apply commands against the local directories.

## Recommendation:

Change kubectl apply install methods to support Kustomize allowing users to `kubectl customize https://github.com/pulumi/pulumi-kubernetes-operator` or similar single command to deploy the operator without requiring locally cloning repositories or other un-necessary steps.

**Comment by EronWright** [comment]
Kustomize bases are now available in `/operator/config`.  We also create a rendered version of the `quickstart` kustomization into `deploy/yaml/manifest.yaml`.
