### ISSUE TITLE
Allow adding role and rolebinding for flux source access

### ISSUE THREAD

**Issue by budimanjojo** [pulumi/pulumi-kubernetes-operator#479]
## Hello!
Currently the helm chart doesn't include any way to allow the operator to access flux source. It would be good to include it.

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

### Affected area/feature

```[tasklist]
### Tasks
```

**Comment by rquitales** [comment]
Hello @budimanjojo,

Thank you for suggesting this enhancement.The addition of Helm chart support is a new supported installation method, so thanks for pointing out the lack of Flux source support - we'll look into adding this soon.

cc @dirien who implemented the initial Helm chart support.

**Comment by dirien** [comment]
Np, @budimanjojo,

let me create a PR for this!

**Comment by dirien** [comment]
Hey @budimanjojo and @rquitales,

here is the PR https://github.com/pulumi/pulumi-kubernetes-operator/pull/480

OCI chart version 0.2.0 should container access (get,list,watch) to the Flux Source.

**Comment by budimanjojo** [comment]
Thanks!

**Comment by dirien** [comment]
@budimanjojo 0.7.0 😅
