### ISSUE TITLE
Add resource requests/limits for controller pods

### ISSUE THREAD

**Issue by rquitales** [pulumi/pulumi-kubernetes-operator#498]
## Issue details

Currently, our deployment manifests do not specify [resource/memory/ephemeral-storage requests and limits](https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#requests-and-limits). We should find reasonable values for these, and update our deployment manifests.

**Comment by cleverguy25** [comment]
Added to epic https://github.com/pulumi/pulumi-kubernetes-operator/issues/586

**Comment by rquitales** [comment]
Note: our controller manager pod already have these values (ref: https://github.com/pulumi/pulumi-kubernetes-operator/blob/50080c3596256ae99947fb97140242d0b513d1e0/operator/config/manager/manager.yaml#L77-L83)
