### ISSUE TITLE
Provide ability to preserve working directory.

### ISSUE THREAD

**Issue by bacek** [pulumi/pulumi-kubernetes-operator#521]
Pulumi Operator is always cleaning up working directory on reconcile at
https://github.com/pulumi/pulumi-kubernetes-operator/blob/7d9e693bc6e27f1e3881ce350cdf7fbde71b26be/pkg/controller/stack/stack_controller.go#L594C34-L594C34

This leads to additional latency on kubernetes deployments due full recreation of python's venv and installing all dependencies.

It would be nice to be able to provide Stack parameter to preserve working directory between runs.

**Comment by cleverguy25** [comment]
Added to epic https://github.com/pulumi/pulumi-kubernetes-operator/issues/586

**Comment by EronWright** [comment]
@bacek  thanks for your efforts here!

With PKO v2, the architecture has changed in a way that mostly addresses this issue.  Each stack now has a dedicated pod, into which the program source code is cloned, dependencies are installed, and then one or more Pulumi updates are applied.  For some use cases, this leads to better reuse and faster updates.

The pod's base image may also be customized, to pre-install your program's dependencies to further increase performance.

Please give v2 a try, and do tell if it satisfies your goals.  Thanks!
