### ISSUE TITLE
Support custom name for serviceAccount in helm chart

### ISSUE THREAD

**Issue by kerruba-milkman** [pulumi/pulumi-kubernetes-operator#529]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Currently the helm chart uses the helper `pulumi-kubernetes-operator.fullname` to populate the service account name, but the `values.yaml` file provide a `serviceAccount.name` value that is only used if the `serviceAccount.create` is `false`.

Could make sense to use the `serviceAccount.name` field as `.metadata.name`  in the ServiceAccount and fallback to the fullname only if the `serviceAccount.name` field is empty or missing. 

Having to use the `fullnameOverride` value to override the name of the serviceAccount doesn't provide enought flexibility and it could be confusing having both `serviceAccount.create = true`  and `serviceAccount.name = "non-empty-string"`.

**Comment by mjeffryes** [comment]
Thanks for reporting this @kerruba-milkman, I'll add it to our backlog.

**Comment by kerruba-milkman** [comment]
Apparently, there's already an helper function to get the service account name that fallbacks to the fullname in case the serviceAccount.name value is not defined. Maybe it's just a matter of referencing it inside the `sa.yaml` template instead of the `pulumi-kubernetes-operator.fullname` function.

Here the update version: 
```helm
{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "pulumi-kubernetes-operator.serviceAccountName" . }}
  labels:
  {{- include "pulumi-kubernetes-operator.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
```
