### ISSUE TITLE
helm install command doesn't work in docs

### ISSUE THREAD

**Issue by SnoozeFreddo** [pulumi/pulumi-kubernetes-operator#544]
### What happened?

Can't install the operator with the given instructions from the documentation.

### Example

helm repo add pulumi-kubernetes-operator https://pulumi.github.io/pulumi-kubernetes-operator/

### Output of `pulumi about`

Error: looks like "https://pulumi.github.io/pulumi-kubernetes-operator/" is not a valid chart repository or cannot be reached: failed to fetch https://pulumi.github.io/pulumi-kubernetes-operator/index.yaml : 403 Forbidden

### Additional context

It's because its a chart source but not a [chart repository](https://helm.sh/docs/topics/chart_repository/)

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mjeffryes** [comment]
Thanks for filing this ticket @SnoozeFreddo; I wasn't able to find the documentation that suggests running `helm repo add pulumi-kubernetes-operator https://pulumi.github.io/pulumi-kubernetes-operator/` Would you mind pointing me to where you saw that? Alternatively, if you'd like to contribute any improvements to the documentation for this project, we'd be happy to review them!

**Comment by mjeffryes** [comment]
Update: I did manage to find the offending instructions here: https://github.com/pulumi/pulumi-kubernetes-operator/blob/5fd9efc38a2420048e5fb69cc0b444fd6a8a252b/deploy/helm/pulumi-operator/README.md?plain=1#L22
