### ISSUE TITLE
`npm install` runs all the time

### ISSUE THREAD

**Issue by v-yarotsky** [pulumi/pulumi-kubernetes-operator#549]
### What happened?

I have pulumi-kubernetes-operator managing 4 stacks from 2 TypeScript programs (fetched from git).
Even if there are no changes to the git repo, the pod keeps continuously running `npm install`
This does not seem desirable.

### Example

All screenshots were taken around the same time.
<img width="940" alt="image" src="https://github.com/pulumi/pulumi-kubernetes-operator/assets/472161/a747b12a-85de-4c14-8a33-9a78e87ab79b">
<img width="645" alt="image" src="https://github.com/pulumi/pulumi-kubernetes-operator/assets/472161/f3a54420-f6b5-4e1b-8c48-e1c62f570f3f">
<img width="393" alt="image" src="https://github.com/pulumi/pulumi-kubernetes-operator/assets/472161/5b51f125-4c3b-48fc-a5d2-0d9363e979ee">
<img width="960" alt="image" src="https://github.com/pulumi/pulumi-kubernetes-operator/assets/472161/2a4787cd-717a-4228-ae30-bf984c28219d">

I have the following dependencies in my `package.json` in the root of the repo where the pulumi programs reside:
```
...
    "@pulumi/keycloak": "^5.2.1",
    "@pulumi/kubernetes": "^4.5.2",
    "@pulumi/pulumi": "3.91",
...    
```

### Output of `pulumi about`

Probably not relevant for this case;
I'm using version 0.5.0 via the [Helm chart](https://github.com/pulumi/pulumi-kubernetes-operator/releases/tag/pulumi-kubernetes-operator-0.5.0).

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mjeffryes** [comment]
Thanks for filing the report @v-yarotsky. Have you checked if the issue reproduces on a fresh cluster? It might also be interesting to try to run a manual preview for the stacks to see if there is and to check the interval for the reconcile loop.

**Comment by v-yarotsky** [comment]
After taking a brief look at the code, it seems like this is by design.
On each iteration of the Reconcile loop[^1], `reconcileStackSession.setupWorkspace`[^2] is called, which in turn calls `reconcileStackSession.InstallProjectDependencies`[^3]. All of that is happening _before_ checking whether the current commit matches the last applied one[^4].

[^1]: https://github.com/pulumi/pulumi-kubernetes-operator/blob/758a51441e9537133fe8bf7df28e7183ef057a54/pkg/controller/stack/stack_controller.go#L635
[^2]: https://github.com/pulumi/pulumi-kubernetes-operator/blob/758a51441e9537133fe8bf7df28e7183ef057a54/pkg/controller/stack/stack_controller.go#L1392
[^3]: https://github.com/pulumi/pulumi-kubernetes-operator/blob/758a51441e9537133fe8bf7df28e7183ef057a54/pkg/controller/stack/stack_controller.go#L1490
[^4]: https://github.com/pulumi/pulumi-kubernetes-operator/blob/758a51441e9537133fe8bf7df28e7183ef057a54/pkg/controller/stack/stack_controller.go#L783

**Comment by cleverguy25** [comment]
Added to epic https://github.com/pulumi/pulumi-kubernetes-operator/issues/586

**Comment by EronWright** [comment]
Good news everyone, we just release a preview of Pulumi Kubernetes Operator v2. This new release has a whole-new architecture that uses pods as the execution environment, and seeks to retain the pod across stack operations.  Installation happens once whenever a new commit is observed by the system. It is also now possible to create a custom docker image with your bits pre-installed, to further increase performance.

Please read the announcement blog post for more information:
https://www.pulumi.com/blog/pulumi-kubernetes-operator-2-0/

Would love to hear your feedback!  Feel free to engage with us on the #kubernetes channel of the [Pulumi Slack workspace](https://slack.pulumi.com/). 
cc @v-yarotsky @rodolfototaro @ainthapanya-sqc
