### ISSUE TITLE
dependency patching

### ISSUE THREAD

**Issue by GeoffMillerAZ** [pulumi/pulumi-kubernetes-operator#555]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

1.14.0 could stand some patching on it's dependencies. Please see the following scan results:

Scan results available on request

### Affected area/feature

Software Compositional Analysis

**Comment by blampe** [comment]
@GeoffMillerAZ can you please include the dependencies you'd like to see patched?

**Comment by mjeffryes** [comment]
@GeoffMillerAZ If the list/scan result is sensitive, perhaps you can post on in internal issue? Or should we just close this out for now?
