### ISSUE TITLE
ProjectRepoAccessTokenSecret in the StackSpec should be a k8s Secret

### ISSUE THREAD

**Issue by metral** [pulumi/pulumi-kubernetes-operator#58]
Currently to use a Git AccessToken to pull private repos or to not be rate-limited is configurable via `ProjectRepoAccessTokenSecret`. However, this is a raw field that should be stored in a k8s Secret like done for the Pulumi API token and any other cloud provider credentials.

https://github.com/pulumi/pulumi-kubernetes-operator/blob/34b881610e87f0734c80a329cfdf5ce4c95b4f5d/pkg/controller/stack/stack_controller.go#L173-L178

Should store the AccessToken in a newly created k8s Secret e.g. how the pulumi API access token is done:

https://github.com/pulumi/pulumi-kubernetes-operator/blob/34b881610e87f0734c80a329cfdf5ce4c95b4f5d/pkg/controller/stack/stack_controller.go#L141-L156

**Comment by rodcloutier** [comment]
@metral Seems that `ProjectSourceOptions` is not used anymore. 
I guess this issue should be closed and the `ProjectSourceOptions` struct removed.

**Comment by metral** [comment]
Thanks for your feedback! It's much appreciated.

The observation about `ProjectSourceOptions` is correct, and we should remove it, along with closing this issue.
