### ISSUE TITLE
[Epic] Kubernetes Operator Core Functionality Enhancements (PKOv2)

### ISSUE THREAD

**Issue by rquitales** [pulumi/pulumi-kubernetes-operator#586]
## Overview

Usage of the Pulumi Kubernetes Operator (PKO) has high friction due to a number of challenges for users. There are numerous performance enhancements that could be adopted by PKO, metrics and logging can sometimes be lacking as well as multi-tenancy concerns. We believe that targeted investments in this project can improve the user experience for users materially. By strengthening our core functionality, we can confidently embark on more ambitious innovations within PKO in the future.

Effort: 5 eng weeks

## Key KPIs

1. Numerous top-voted enhancement requests can be closed, which pertain to scalability and isolation concerns.
2. Significantly improved stack reconciliation performance, esp. in use cases involving numerous stacks, long-running or complex stacks, slow-changing dependencies and/or source code, and period reconciliations.
3. multi-tenancy support within a Kubernetes cluster; stacks are significantly more isolated across namespaces, using a dedicated execution environment, no cross-namespace secret exposure, and non-root execution.

## Key Stakeholders

Engineers: @EronWright 

Approvers: @mjeffryes 

## Key Deliverables

1. An RPC server providing an "automation" API for stack operations.
2. A Kubernetes operator providing low-level automation primitives - a `Workspace` to provision an execution environment for a given program, an `Update` to drive one deployment operation against a given workspace, etc.
3. A revised Stack operator that use the lower-level primitives to reconcile its stacks. The Stack API may see some changes to accommodate the architecture change.
4. A new "v2 beta" release of the operator, with supporting materials (blog post, migration guide).

### References 📔

- [x] [Project View](https://github.com/orgs/pulumi/projects/166/)
- [ ] PR/FAQ 
- [x] [Design Doc](https://docs.google.com/document/d/1hHOgs9uDsvAbj89D-b4WjVG9GnoJ7_cy5FKGOeSAfRg/edit?usp=sharing)
- [ ] UX Designs 
- [ ] Decision Log

**Comment by cleverguy25** [comment]
Adding item https://github.com/pulumi/pulumi-kubernetes-operator/issues/606

**Comment by cleverguy25** [comment]
Adding item https://github.com/pulumi/pulumi-kubernetes-operator/issues/607

**Comment by cleverguy25** [comment]
Adding item https://github.com/pulumi/pulumi-kubernetes-operator/issues/606

**Comment by cleverguy25** [comment]
Adding item https://github.com/pulumi/pulumi-kubernetes-operator/issues/612

**Comment by cleverguy25** [comment]
Adding item https://github.com/pulumi/pulumi-kubernetes-operator/issues/613

**Comment by cleverguy25** [comment]
Adding item https://github.com/pulumi/pulumi-kubernetes-operator/issues/573

**Comment by cleverguy25** [comment]
Adding item https://github.com/pulumi/pulumi-kubernetes-operator/issues/576

**Comment by cleverguy25** [comment]
Adding item https://github.com/pulumi/pulumi-kubernetes-operator/issues/607

**Comment by cleverguy25** [comment]
Adding item https://github.com/pulumi/pulumi-kubernetes-operator/issues/608

**Comment by cleverguy25** [comment]
Adding item https://github.com/pulumi/pulumi-kubernetes-operator/issues/609

**Comment by cleverguy25** [comment]
Adding item https://github.com/pulumi/pulumi-kubernetes-operator/issues/610

**Comment by cleverguy25** [comment]
Adding item https://github.com/pulumi/pulumi-kubernetes-operator/issues/611

**Comment by cleverguy25** [comment]
Adding item https://github.com/pulumi/pulumi-kubernetes-operator/issues/616

**Comment by cleverguy25** [comment]
Adding item https://github.com/pulumi/pulumi-kubernetes-operator/issues/461

**Comment by cleverguy25** [comment]
Adding item https://github.com/pulumi/pulumi-kubernetes-operator/issues/617

**Comment by cleverguy25** [comment]
Adding item https://github.com/pulumi/pulumi-kubernetes-operator/issues/618

**Comment by cleverguy25** [comment]
Adding item https://github.com/pulumi/pulumi-kubernetes-operator/issues/619

**Comment by cleverguy25** [comment]
Adding item https://github.com/pulumi/pulumi-kubernetes-operator/issues/615

**Comment by cleverguy25** [comment]
Adding item https://github.com/pulumi/pulumi-kubernetes-operator/issues/621

**Comment by cleverguy25** [comment]
Adding item https://github.com/pulumi/pulumi-kubernetes-operator/issues/515

**Comment by cleverguy25** [comment]
Adding item https://github.com/pulumi/pulumi-kubernetes-operator/issues/501

**Comment by cleverguy25** [comment]
Adding item https://github.com/pulumi/pulumi-kubernetes-operator/issues/549

**Comment by cleverguy25** [comment]
Adding item https://github.com/pulumi/pulumi-kubernetes-operator/issues/78

**Comment by cleverguy25** [comment]
Adding item https://github.com/pulumi/pulumi-kubernetes-operator/issues/498

**Comment by cleverguy25** [comment]
Adding item https://github.com/pulumi/pulumi-kubernetes-operator/issues/564

**Comment by cleverguy25** [comment]
Adding item https://github.com/pulumi/pulumi-kubernetes-operator/issues/451

**Comment by cleverguy25** [comment]
Adding item https://github.com/pulumi/pulumi-kubernetes-operator/issues/521

**Comment by cleverguy25** [comment]
Adding item https://github.com/pulumi/pulumi-kubernetes-operator/issues/447

**Comment by cleverguy25** [comment]
Adding item https://github.com/pulumi/pulumi-kubernetes-operator/issues/627

**Comment by cleverguy25** [comment]
Adding item https://github.com/pulumi/pulumi-kubernetes-operator/issues/368

**Comment by cleverguy25** [comment]
Adding item https://github.com/pulumi/pulumi-kubernetes-operator/issues/649

**Comment by cleverguy25** [comment]
Adding item https://github.com/pulumi/pulumi-kubernetes-operator/issues/635

**Comment by cleverguy25** [comment]
Adding item https://github.com/pulumi/pulumi-kubernetes-operator/issues/650

**Comment by cleverguy25** [comment]
Adding item https://github.com/pulumi/pulumi-kubernetes-operator/issues/634

**Comment by cleverguy25** [comment]
Adding item https://github.com/pulumi/pulumi-kubernetes-operator/issues/651

**Comment by cleverguy25** [comment]
Adding item https://github.com/pulumi/pulumi-kubernetes-operator/issues/652

**Comment by cleverguy25** [comment]
Adding item https://github.com/pulumi/pulumi-kubernetes-operator/issues/653

**Comment by cleverguy25** [comment]
Adding item https://github.com/pulumi/pulumi-kubernetes-operator/issues/654

**Comment by cleverguy25** [comment]
Adding item https://github.com/pulumi/pulumi-kubernetes-operator/issues/655

**Comment by cleverguy25** [comment]
Adding item https://github.com/pulumi/pulumi-kubernetes-operator/issues/657

**Comment by cleverguy25** [comment]
Adding item https://github.com/pulumi/pulumi-kubernetes-operator/issues/666

**Comment by cleverguy25** [comment]
Adding item https://github.com/pulumi/pulumi-kubernetes-operator/issues/672

**Comment by cleverguy25** [comment]
Adding item https://github.com/pulumi/pulumi-kubernetes-operator/issues/674

**Comment by cleverguy25** [comment]
Adding item https://github.com/pulumi/pulumi-kubernetes-operator/issues/675

**Comment by cleverguy25** [comment]
Adding item https://github.com/pulumi/pulumi-kubernetes-operator/issues/677

**Comment by cleverguy25** [comment]
Adding item https://github.com/pulumi/pulumi-kubernetes-operator/issues/680

**Comment by cleverguy25** [comment]
Adding item https://github.com/pulumi/pulumi-kubernetes-operator/issues/684

**Comment by cleverguy25** [comment]
Adding item https://github.com/pulumi/pulumi-kubernetes-operator/issues/685

**Comment by cleverguy25** [comment]
Adding item https://github.com/pulumi/pulumi-kubernetes-operator/issues/687

**Comment by cleverguy25** [comment]
Adding item https://github.com/pulumi/pulumi-kubernetes-operator/issues/690

**Comment by cleverguy25** [comment]
Adding item https://github.com/pulumi/pulumi-kubernetes-operator/issues/694

**Comment by cleverguy25** [comment]
Adding item https://github.com/pulumi/pulumi-kubernetes-operator/issues/696

**Comment by cleverguy25** [comment]
Adding item https://github.com/pulumi/pulumi-kubernetes-operator/issues/697

**Comment by cleverguy25** [comment]
Adding item https://github.com/pulumi/pulumi-kubernetes-operator/issues/698

**Comment by cleverguy25** [comment]
Adding item https://github.com/pulumi/pulumi-kubernetes-operator/issues/700

**Comment by cleverguy25** [comment]
Adding item https://github.com/pulumi/pulumi-kubernetes-operator/issues/701

**Comment by cleverguy25** [comment]
Adding item https://github.com/pulumi/pulumi-kubernetes-operator/issues/704

**Comment by cleverguy25** [comment]
Adding item https://github.com/pulumi/pulumi-kubernetes-operator/issues/710

**Comment by cleverguy25** [comment]
Adding item https://github.com/pulumi/pulumi-kubernetes-operator/issues/469

**Comment by cleverguy25** [comment]
Adding item https://github.com/pulumi/pulumi-kubernetes-operator/issues/715

**Comment by cleverguy25** [comment]
Adding item https://github.com/pulumi/pulumi-kubernetes-operator/issues/716

**Comment by cleverguy25** [comment]
Adding item https://github.com/pulumi/pulumi-kubernetes-operator/issues/720

**Comment by cleverguy25** [comment]
Adding item https://github.com/pulumi/pulumi-kubernetes-operator/issues/721

**Comment by cleverguy25** [comment]
Adding item https://github.com/pulumi/pulumi-kubernetes-operator/issues/727

**Comment by cleverguy25** [comment]
Adding item https://github.com/pulumi/pulumi-kubernetes-operator/issues/730

**Comment by cleverguy25** [comment]
Adding item https://github.com/pulumi/pulumi-kubernetes-operator/issues/732

**Comment by cleverguy25** [comment]
Adding item https://github.com/pulumi/pulumi-kubernetes-operator/issues/582

**Comment by cleverguy25** [comment]
Adding item https://github.com/pulumi/pulumi-kubernetes-operator/issues/425

**Comment by cleverguy25** [comment]
Adding item https://github.com/pulumi/pulumi-kubernetes-operator/issues/396

**Comment by cleverguy25** [comment]
Adding item https://github.com/pulumi/pulumi-kubernetes-operator/issues/393

**Comment by cleverguy25** [comment]
Adding item https://github.com/pulumi/pulumi-kubernetes-operator/issues/735

**Comment by cleverguy25** [comment]
Adding item https://github.com/pulumi/pulumi-kubernetes-operator/issues/736

**Comment by cleverguy25** [comment]
Adding item https://github.com/pulumi/pulumi-kubernetes-operator/issues/737

**Comment by cleverguy25** [comment]
Adding item https://github.com/pulumi/pulumi-kubernetes-operator/issues/738

**Comment by cleverguy25** [comment]
Adding item https://github.com/pulumi/pulumi-kubernetes-operator/issues/739

**Comment by cleverguy25** [comment]
Adding item https://github.com/pulumi/pulumi-kubernetes-operator/issues/740

**Comment by EronWright** [comment]
This is done and shipped as PKOv2 ([v2.0.0-beta.1](https://github.com/pulumi/pulumi-kubernetes-operator/releases/tag/v2.0.0-beta.1)) and [accompanying blog post](https://www.pulumi.com/blog/pulumi-kubernetes-operator-2-0/).  We closed approximately a dozen outstanding issues. We reached out to known users of PKO, and were contacted by others, to gather some feedback in preparation for a "GA" release to come soon.

Here's a tracking issue for potential follow-ups:
https://github.com/pulumi/pulumi-kubernetes-operator/issues/734
