### ISSUE TITLE
CRDs included in helm chart 0.7.3 are not the latest

### ISSUE THREAD

**Issue by kerruba-milkman** [pulumi/pulumi-kubernetes-operator#596]
### What happened?

During the installation of the pulumi-kubernetes-operator using the Helm Chart at the latest currently available version (0.7.3), the installed CRDs are not the latest available. Checking the repository, seems like the CRDS packed in the helm chart are not the same as those in `deploy/crds`.
Also documentation reference the latest version of the CRDs, with features that are not available in the previous version (like `prerequisites` field)

### Example

Helm crds: https://github.com/pulumi/pulumi-kubernetes-operator/tree/master/deploy/helm/pulumi-operator/crds
Latest crds: https://github.com/pulumi/pulumi-kubernetes-operator/tree/master/deploy/crds

### Output of `pulumi about`

I'm using the version 0.7.3 of the pulumi-kubernetes-operator helm chart

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by blampe** [comment]
Good catch @kerruba-milkman! We'll update our generate scripts to keep these in sync.

**Comment by rquitales** [comment]
`v0.8.0` of the Helm chart now contains the updated CRDs. Newer helm chart releases will also be synced if there are CRD updates.
