### ISSUE TITLE
gRPC layer for Automation API

### ISSUE THREAD

**Issue by EronWright** [pulumi/pulumi-kubernetes-operator#606]
This issue tracks the implementation tasks for a new gRPC layer for the Automation API; see [Proposal](https://docs.google.com/document/d/1hHOgs9uDsvAbj89D-b4WjVG9GnoJ7_cy5FKGOeSAfRg/edit?usp=sharing).

**Comment by cleverguy25** [comment]
Added to epic https://github.com/pulumi/pulumi-kubernetes-operator/issues/586

**Comment by cleverguy25** [comment]
Added to epic https://github.com/pulumi/pulumi-kubernetes-operator/issues/586
