### ISSUE TITLE
Implement graceful termination for the server, canceling outstanding operations

### ISSUE THREAD

**Issue by EronWright** [pulumi/pulumi-kubernetes-operator#607]
When the grpc server receives a shutdown signal (SIGINT), it should gracefully shutdown. It should not accept new RPC requests, and should wait for outstanding requests to complete.

Shutdown is usually due to a planned disruption, e.g. workspace pod termination due to a change to the project source or for node maintenance.

Ideally, any outstanding Pulumi deployment operation would be sent a CTRL-C signal to give it a chance to wind down gracefully. That's an unimplemented aspect of the core auto API: https://github.com/pulumi/pulumi/issues/13160

**Comment by cleverguy25** [comment]
Added to epic https://github.com/pulumi/pulumi-kubernetes-operator/issues/586

**Comment by cleverguy25** [comment]
Added to epic https://github.com/pulumi/pulumi-kubernetes-operator/issues/586
