### ISSUE TITLE
Develop the grpc proto specification

### ISSUE THREAD

**Issue by EronWright** [pulumi/pulumi-kubernetes-operator#610]
Finalize the subset of auto API methods to be exposed via gRPC, based on the needs of the PKO project.

- `WhoAmI`
- `Info`
- `Refresh`
- `Preview`
- `Up`
- `Destroy`

If stack selection happens implicitly during the operation, there's probably no need for any explicit stack management commands.

Use streaming responses as appropriate, e.g. for deployment operations where an event stream is available.

**Comment by cleverguy25** [comment]
Added to epic https://github.com/pulumi/pulumi-kubernetes-operator/issues/586
