### ISSUE TITLE
Stack controller for PKOv2

### ISSUE THREAD

**Issue by EronWright** [pulumi/pulumi-kubernetes-operator#613]
This issue tracks implementation tasks for porting the Stack API and controller to use the new Automation API.

**Comment by cleverguy25** [comment]
Added to epic https://github.com/pulumi/pulumi-kubernetes-operator/issues/586

**Comment by EronWright** [comment]
This is done: https://github.com/pulumi/pulumi-kubernetes-operator/commit/e850d02f25f2302b9e2a30c6345d08e1cbc64c77
