### ISSUE TITLE
Update Stack controller

### ISSUE THREAD

**Issue by EronWright** [pulumi/pulumi-kubernetes-operator#615]
Update the Stack controller to use the new auto API, e.g. to create workspaces and to drive update operations.

**Comment by cleverguy25** [comment]
Added to epic https://github.com/pulumi/pulumi-kubernetes-operator/issues/586

**Comment by EronWright** [comment]
Done: https://github.com/pulumi/pulumi-kubernetes-operator/commit/e850d02f25f2302b9e2a30c6345d08e1cbc64c77
