### ISSUE TITLE
Prepare the "v2" codebase

### ISSUE THREAD

**Issue by EronWright** [pulumi/pulumi-kubernetes-operator#618]
Initialize the codebase in preparation for a new apigroup, tentatively named `auto.pulumi.com/v1alpha1`.

The current operator codebase uses a fairly outdated version of the Operator SDK, and the layout is "single-group". For both reasons, it may make sense to create a new codebase for v2, likely in the same repo.

Porting the existing operator code is beyond the scope of this issue.

**Comment by cleverguy25** [comment]
Added to epic https://github.com/pulumi/pulumi-kubernetes-operator/issues/586

**Comment by EronWright** [comment]
Update: I'm using a simple provisional layout that keeps the new operator in a separate directory but in the same repo.  When we turn to porting to the existing operator code, we will finalize the overall layout.

One change yet to be made to the new operator layout (in its own right) is to use a [multi-group layout](https://book.kubebuilder.io/migration/multi-group), to be prepared to port the high-level api group into the new operator codebase.
