### ISSUE TITLE
Develop the workspace API and controller

### ISSUE THREAD

**Issue by EronWright** [pulumi/pulumi-kubernetes-operator#619]
Implementation task for the `Workspace` API, per [design doc](https://docs.google.com/document/d/1hHOgs9uDsvAbj89D-b4WjVG9GnoJ7_cy5FKGOeSAfRg/edit#heading=h.o1cg2qaija75).

**Comment by cleverguy25** [comment]
Added to epic https://github.com/pulumi/pulumi-kubernetes-operator/issues/586

**Comment by EronWright** [comment]
The workspace controller is functionally complete, what's remaining is some test code and a good readme.
