### ISSUE TITLE
Develop the Update API and controller

### ISSUE THREAD

**Issue by EronWright** [pulumi/pulumi-kubernetes-operator#620]
Implementation task for the Update API, per [design doc](https://docs.google.com/document/d/1hHOgs9uDsvAbj89D-b4WjVG9GnoJ7_cy5FKGOeSAfRg/edit#heading=h.m6uekejf5h6a).

**Comment by cleverguy25** [comment]
Added to epic https://github.com/pulumi/pulumi-kubernetes-operator/issues/586

**Comment by EronWright** [comment]
A basic controller for `Update` API is in place, but I'm keeping it simple for now until we revise the stack controller to use it. The outstanding functionality is:
1. Support for "dependencies" to ensure that updates are ordered.
2. Support for the various operation args, e.g. `--target`.
