### ISSUE TITLE
Design the Stack v2alpha1 API

### ISSUE THREAD

**Issue by EronWright** [pulumi/pulumi-kubernetes-operator#621]
Design the Stack v2alpha1 API, incorporating any changes necessary to be able to use the new auto API. Such changes likely include:
- disallowing cross-namespace references (e.g. to secrets or configmaps)
- removing deprecated elements from v1 api

Also, exposing new workspace feature:
- pod resources
- docker image

**Comment by cleverguy25** [comment]
Added to epic https://github.com/pulumi/pulumi-kubernetes-operator/issues/586

**Comment by EronWright** [comment]
An implementation of the revised Stack controller was written to serve the existing v1 version.  Looks like there's no pressing need to introduce a v2alpha1 version, where we would need to deal with deprecations, structured config, etc. I'm going to close this issue for now.
