### ISSUE TITLE
Upgrade k8s dependencies

### ISSUE THREAD

**Issue by blampe** [pulumi/pulumi-kubernetes-operator#634]
In order for existing Stack Controller to work with the new Automation APIs we'll need to bump its dependencies.

Pre-req for #615

**Comment by rquitales** [comment]
An older branch that handles updating the k8s/kubebuilder deps which could be used as a reference:
https://github.com/pulumi/pulumi-kubernetes-operator/tree/rquitales/update-operator

**Comment by EronWright** [comment]
This was done by porting the stack controller into a new codebase in the `operator/` directory, based on kubebuilder v4.1.

https://github.com/pulumi/pulumi-kubernetes-operator/commit/e850d02f25f2302b9e2a30c6345d08e1cbc64c77

**Comment by cleverguy25** [comment]
Added to epic https://github.com/pulumi/pulumi-kubernetes-operator/issues/586
