### ISSUE TITLE
Re-arrange code for multiple API groups

### ISSUE THREAD

**Issue by blampe** [pulumi/pulumi-kubernetes-operator#635]
Pre-req for #615

**Comment by EronWright** [comment]
Done: https://github.com/pulumi/pulumi-kubernetes-operator/commit/e850d02f25f2302b9e2a30c6345d08e1cbc64c77

**Comment by cleverguy25** [comment]
Added to epic https://github.com/pulumi/pulumi-kubernetes-operator/issues/586
