### ISSUE TITLE
Optimize stack configuration step

### ISSUE THREAD

**Issue by EronWright** [pulumi/pulumi-kubernetes-operator#650]
The Workspace controller is expected to configure the stack with the supplied configuration values.  The current implementation calls the `SetAllConfig` RPC method for each config item, and this is proving to be slow.  Would be nice to set in bulk, but be considerate about the ordering of the config elements.

Also, consider enhancing the Workspace config block to natively understand configmap/secret refs.  Today, the Stack controller handles references via general extensibility, i.e. via the pod template. A first-class option would be better.

**Comment by cleverguy25** [comment]
Added to epic https://github.com/pulumi/pulumi-kubernetes-operator/issues/586
