### ISSUE TITLE
Implement the Program API

### ISSUE THREAD

**Issue by EronWright** [pulumi/pulumi-kubernetes-operator#651]
The Program API serves as way to write an inline YAML program to be deployed via the Stack API (see [docs](https://www.pulumi.com/docs/using-pulumi/continuous-delivery/pulumi-kubernetes-operator/#using-a-program-object)).

We need a way to feed the program to the workspace pod, during pod initialization. A couple of possible ways:
1. Have the init container get the `Program` object directly from the API server. This has an RBAC implication.
2. Have the program controller produce a downloadable artifact, akin to how `GitRepository` serves an artifact, and download the artifact as we do with Flux.  
 
I have a preference for (2). Note that the `Program` CRD doesn't have a status block as of yet, nor does it have a controller.

For reference, here's how the `GitRepository` CR works:
```yaml
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  creationTimestamp: "2024-07-25T17:06:15Z"
  finalizers:
    - finalizers.fluxcd.io
  generation: 1
  name: pulumi-examples
  namespace: default
  resourceVersion: "2005488"
  uid: 1b67a048-8ec1-4486-8fcc-79858a48fa35
spec:
  interval: 5m0s
  ref:
    branch: master
  timeout: 60s
  url: https://github.com/pulumi/examples.git
status:
  artifact:
    digest: sha256:bcbed45526b241ab3366707b5a58c900e9d60a1d5c385cdfe976b1306584b454
    lastUpdateTime: "2024-09-04T17:32:18Z"
    path: gitrepository/default/pulumi-examples/f143bd369afcb5455edb54c2b90ad7aaac719339.tar.gz
    revision: master@sha1:f143bd369afcb5455edb54c2b90ad7aaac719339
    size: 48988266
    url: http://source-controller.flux-system.svc.cluster.local./gitrepository/default/pulumi-examples/f143bd369afcb5455edb54c2b90ad7aaac719339.tar.gz
  conditions:
    - lastTransitionTime: "2024-09-05T21:12:31Z"
      message: stored artifact for revision 'master@sha1:f143bd369afcb5455edb54c2b90ad7aaac719339'
      observedGeneration: 1
      reason: Succeeded
      status: "True"
      type: Ready
    - lastTransitionTime: "2024-09-04T17:32:18Z"
      message: stored artifact for revision 'master@sha1:f143bd369afcb5455edb54c2b90ad7aaac719339'
      observedGeneration: 1
      reason: Succeeded
      status: "True"
      type: ArtifactInStorage
  observedGeneration: 1
```

**Comment by cleverguy25** [comment]
Added to epic https://github.com/pulumi/pulumi-kubernetes-operator/issues/586
