### ISSUE TITLE
Setup an "in-cluster" kubeconfig within the workspace pod

### ISSUE THREAD

**Issue by EronWright** [pulumi/pulumi-kubernetes-operator#652]
PKOv1 makes an effort to create a kubeconfig within the operator's own container at startup (see [`setupInClusterKubeconfig`](https://github.com/pulumi/pulumi-kubernetes-operator/blob/fb0a7f1246cb3f99e2a73f8460ca498f8132579e/pkg/controller/stack/stack_controller.go#L1886)). The rationale is, I believe, to facilitate the use of the pulumi-kubernetes provider in your program.

Since the program now runs in the workspace pod, we may need to do similarly, either by adding a default kubeconfig to the pu/pu image, or by creating a kubeconfig during workspace initialization. Of course, this is simply an "in-cluster" connection to the API server using the pod's service account.

**Comment by cleverguy25** [comment]
Added to epic https://github.com/pulumi/pulumi-kubernetes-operator/issues/586

**Comment by EronWright** [comment]
@julienp for your awareness

**Comment by blampe** [comment]
Can write some code in the agent to generate an in-cluster config.

**Comment by rquitales** [comment]
This work is not required for the Pulumi Kubernetes provider to work with the cluster that the pod is running in. Our default config loading rules (from client-go) in p-k will already attempt to use the inCluster credentials if it can't find a valid kubeconfig. I have manually validated this by deploying a `pulumi/pulumi-go` pod, which does not have any Kubernetes tooling installed, and it is able to create k8s resources from a Pulumi program within the same cluster the pod is running in.

Ref to our config loading rules: https://github.com/pulumi/pulumi-kubernetes/blob/74673fdf488bdf3513cd76d6f6d62ae0184faabc/provider/pkg/provider/provider.go#L779-L785
