### ISSUE TITLE
Write tests for the stack controller

### ISSUE THREAD

**Issue by EronWright** [pulumi/pulumi-kubernetes-operator#654]
Write unit tests for the new stack controller's functionality, covering:

- [x] finalization
- [x] processing of the current update
- [x] resync triggers
- [x] periodic re-sync
- [x] updates
- [x] prerequisite stacks
- [x] flux source
- [x] git source (w/ branch polling)
- [ ] envs, secretenvs, envrefs
- [ ] ~program source~

**Comment by cleverguy25** [comment]
Added to epic https://github.com/pulumi/pulumi-kubernetes-operator/issues/586
