### ISSUE TITLE
Implement the Git source

### ISSUE THREAD

**Issue by EronWright** [pulumi/pulumi-kubernetes-operator#655]
The new stack controller doesn't actually support the `git` spec yet; it works only with Flux.  To complete the git support, we need:

- [x] Develop a way to query the git remote to resolve the HEAD of the given branch, ideally without cloning the repo (as is done today).
- [x] Implement support for git auth options, incl. in the workspace pod where the clone operation takes place.

**Comment by cleverguy25** [comment]
Added to epic https://github.com/pulumi/pulumi-kubernetes-operator/issues/586
