### ISSUE TITLE
blog post for new Pulumi Kubernetes Operator

### ISSUE THREAD

**Issue by mjeffryes** [pulumi/pulumi-kubernetes-operator#657]
Write a blog post announcing the new capabilities of the Pulumi Kubernetes operator

**Comment by cleverguy25** [comment]
Added to epic https://github.com/pulumi/pulumi-kubernetes-operator/issues/586

**Comment by EronWright** [comment]
Here's the blog post:
https://www.pulumi.com/blog/pulumi-kubernetes-operator-2-0/
