### ISSUE TITLE
Add a workspace template to the Stack

### ISSUE THREAD

**Issue by EronWright** [pulumi/pulumi-kubernetes-operator#666]
Add a `workspaceTemplate` to the Stack spec, to allow for general extensibility of the stack's workspace.

The stack controller should merge the provided template using strategic merge patch, similarly to how the workspace controller merges the pod template ([ref](https://github.com/pulumi/pulumi-kubernetes-operator/blob/e850d02f25f2302b9e2a30c6345d08e1cbc64c77/operator/internal/controller/auto/workspace_controller.go#L532-L538)).

**Comment by cleverguy25** [comment]
Added to epic https://github.com/pulumi/pulumi-kubernetes-operator/issues/586
