### ISSUE TITLE
implement a back-off for re-attempts at a failed update

### ISSUE THREAD

**Issue by EronWright** [pulumi/pulumi-kubernetes-operator#677]
The stack controller seems to retry failed updates without using a backoff.  The built-in reconciliation backoff kicks in only when reconcile returns an error, which isn't the case here. 

Consider looking at `lastUpdate.endTime` to implement a backoff strategy when `lastUpdate.status` is `failed`. Assumedly the stack would stay marked as Reconciling (rather than Stalled).

**Comment by cleverguy25** [comment]
Added to epic https://github.com/pulumi/pulumi-kubernetes-operator/issues/586
