### ISSUE TITLE
Remove  v1 code

### ISSUE THREAD

**Issue by EronWright** [pulumi/pulumi-kubernetes-operator#680]
- [x] Remove `/pkg`
- [x] Remove`/cmd`
- [x] Update docs/build.md
- [x] Generate CRDs to `/deploy`
- [x] Update API references in docs/ (crdoc)

Later, with tests:
- go.mod

**Comment by cleverguy25** [comment]
Added to epic https://github.com/pulumi/pulumi-kubernetes-operator/issues/586
