### ISSUE TITLE
Update PKO installer as necessary

### ISSUE THREAD

**Issue by EronWright** [pulumi/pulumi-kubernetes-operator#684]
- [x] fixups to be able to push the operator image
- [x] a new pulmui deploy app that uses the kustomization manifests in operator/config
- [x] updated helm chart
  - [x] cluster rbac
  - [x] namespaced rbac
  - [x] security context
  - [x] aggregated roles
- [x] updated install.yaml in deploy/yaml

**Comment by cleverguy25** [comment]
Added to epic https://github.com/pulumi/pulumi-kubernetes-operator/issues/586

**Comment by EronWright** [comment]
This is done.
