### ISSUE TITLE
Update the "max reconciles" for each controller

### ISSUE THREAD

**Issue by EronWright** [pulumi/pulumi-kubernetes-operator#721]
The Workspace and Update controllers have blocking operations in their loops; they connect and invoke RPC operation(s).  Therefore we should increase the number of concurrent reconciles.  Meanwhile, the Stack controller is now non-blocking and so should be decreased; in v1 it had blocking operations.

suggested: 25, 25, 10

**Comment by cleverguy25** [comment]
Added to epic https://github.com/pulumi/pulumi-kubernetes-operator/issues/586
