### ISSUE TITLE
V2 operator/agent should set custom user-agent for Pulumi operations

### ISSUE THREAD

**Issue by rquitales** [pulumi/pulumi-kubernetes-operator#727]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

We should update our agent server code to also use a custom user-agent string for Pulumi auto api operations. This was done in v1 of the operator. Ref: https://github.com/pulumi/pulumi-kubernetes-operator/blob/2ca775387e522fd5c29668a85bfba2f8fd791848/pkg/controller/stack/stack_controller.go#L1619-L1628

**Comment by EronWright** [comment]
@rquitales I believe this is already done, for example:

https://github.com/pulumi/pulumi-kubernetes-operator/blob/17d8dc8ee6ee690d8c20d1ccb2a13d0144d4c434/agent/pkg/server/server.go#L513

**Comment by EronWright** [comment]
I suppose we should add the version info to make the user agent be equivalent to v1:

```
execAgent               = fmt.Sprintf("pulumi-kubernetes-operator/%s", version.Version)
```

**Comment by cleverguy25** [comment]
Added to epic https://github.com/pulumi/pulumi-kubernetes-operator/issues/586
