### ISSUE TITLE
Report status changes to the operator log

### ISSUE THREAD

**Issue by EronWright** [pulumi/pulumi-kubernetes-operator#732]
Seems like users don't always know to look at status blocks, and assume that the log output represents "progress".  A transient error, for example, may seem like a fatal error due to lack of any subsequent message(s).

Let's ensure that there's some info-level output whenever the system makes progress, maybe producing a warning when the status is abnormal.  Also double-check that the helm chart has INFO level by default.

Closes: https://github.com/pulumi/pulumi-kubernetes-operator/issues/354

**Comment by cleverguy25** [comment]
Added to epic https://github.com/pulumi/pulumi-kubernetes-operator/issues/586
