### ISSUE TITLE
Some stack outputs cannot be saved to Secret

### ISSUE THREAD

**Issue by EronWright** [pulumi/pulumi-kubernetes-operator#743]
### What happened?

Stack outputs have a free-form name, for example an output might be named `foo bar` (i.e. has whitespace). Such outputs cannot be stored into the `Secret` that is associated with the `Update` object, and the controller sees an error from the API Server to the effect that the secret cannot contain a key with an invalid name.

```
data[foo bar]: Invalid value: "foo bar": a valid config key must consist of 
alphanumeric characters, '-', '_' or '.' (e.g. 'key.name',  or 'KEY_NAME',  or 'key-name', 
regex used for validation is '[-._a-zA-Z0-9]+')
```

### Example

Make a simple program that emits an output with an abnormal name.

```yaml/
name: example
runtime: yaml
outputs:
  "foo bar": "baz"
```

### Output of `pulumi about`

```plain
CLI          
Version      3.132.0
Go Version   go1.23.1
Go Compiler  gc

Plugins
KIND      NAME  VERSION
language  yaml  unknown

Host     
OS       darwin
Version  14.5
Arch     arm64

```

### Additional context

The solution is assumedly to sanitize the name to conform with the restriction.  An alternative would be to pack all the outputs into a single key, but that would make the Secret be less useful.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by blampe** [comment]
> The solution is assumedly to sanitize the name to conform with the restriction. An alternative would be to pack all the outputs into a single key, but that would make the Secret be less useful.

Agree sanitizing the key seems the most reasonable.
