### ISSUE TITLE
Move the reconciliation loop to a model where each run executes as a k8s Job

### ISSUE THREAD

**Issue by metral** [pulumi/pulumi-kubernetes-operator#78]
### Problem description

Currently, the reconciliation loop is shared in-process on the operator.

Ideally, a separate Job/Pod would be used instead per loop to avoid shared context issues across loops and runtimes.
See the [design doc](https://docs.google.com/document/d/1cXsamgIbiF7QDXz4mQ7tBpowUt6vgdXY1ZpRcCwF9Pk/edit#heading=h.3772mch6f52j).

**Comment by EronWright** [comment]
Using a `Pod` to execute `pulumi up` may unlock some interesting capabilities.  Some example:
1. mounting of stack-specific volumes to act as an alternate source for the program sources, program data, or even backend state.
2. Stack-specific service accounts.  This would allow us to harden the permissions granted to the operator itself.
3. Clean separation of log output between the operator and the program.

**Comment by viveklak** [comment]
Note that if we support https://github.com/pulumi/pulumi-kubernetes-operator/issues/122 we will have to ensure the secret injection mechanism can mount secrets into the job/pod encapsulating the stack.

**Comment by cleverguy25** [comment]
Added to epic https://github.com/pulumi/pulumi-kubernetes-operator/issues/586

**Comment by EronWright** [comment]
Good news everyone, we just release a preview of Pulumi Kubernetes Operator v2. This new release has a whole-new architecture that uses pods as the execution environment.

Please read the announcement blog post for more information:
https://www.pulumi.com/blog/pulumi-kubernetes-operator-2-0/

Would love to hear your feedback!  Feel free to engage with us on the #kubernetes channel of the [Pulumi Slack workspace](https://slack.pulumi.com/). 
cc @metral @liamawhite @sullivtr @bgagnon @mike-chen-samsung @Alegrowin
