### ISSUE TITLE
Support Python projects without `virtualenv` configuration

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi-kubernetes-operator#79]
The initial implementation of Python support in https://github.com/pulumi/pulumi-kubernetes-operator/pull/77 did not enable support for Python projects that do not have a `virtualenv` configuration, as installing requirements for these projects would require global changes, which are not safe in the operator until reconciliation is performed in separate Jobs.  Once we support stack update isolation, we can bring back support for non-virtualenv Python projects.

**Comment by EronWright** [comment]
Good news everyone, we just released a preview of Pulumi Kubernetes Operator v2. This new release has a whole-new architecture that uses pods as the execution environment. Plugin installation is handled by `pulumi install` uniformly for all project runtimes.

Please read the announcement blog post for more information:
https://www.pulumi.com/blog/pulumi-kubernetes-operator-2-0/

Would love to hear your feedback!  Feel free to engage with us on the #kubernetes channel of the [Pulumi Slack workspace](https://slack.pulumi.com/). 
cc @JonCholas @davide-romanini-milkman @kerruba-milkman
