### ISSUE TITLE
Incoherence between documented behaviour and runtime with Stack.StackStatus.LastUpdate.State field

### ISSUE THREAD

**Issue by rodcloutier** [pulumi/pulumi-kubernetes-operator#98]
### Problem description

According to the documentation/comment, in `StackStatus.LastUpdate.State` field we should see either `succeeded` or `failed`. We instead see the current commit (ie `master`).

https://github.com/pulumi/pulumi-kubernetes-operator/blob/79f0048aa64530e61916efe918bdcccdd538421c/pkg/apis/pulumi/v1alpha1/stack_types.go#L100

This seems to be a misconception and used throughout the code:

Compare with commit
https://github.com/pulumi/pulumi-kubernetes-operator/blob/79f0048aa64530e61916efe918bdcccdd538421c/pkg/controller/stack/stack_controller.go#L217

Assigned a failed message
https://github.com/pulumi/pulumi-kubernetes-operator/blob/79f0048aa64530e61916efe918bdcccdd538421c/pkg/controller/stack/stack_controller.go#L267-L270

Assigned a commit
https://github.com/pulumi/pulumi-kubernetes-operator/blob/79f0048aa64530e61916efe918bdcccdd538421c/pkg/controller/stack/stack_controller.go#L297-L305

**Comment by lukehoban** [comment]
@vivek I believe this was fixed with #107?

**Comment by viveklak** [comment]
Fixed by #107. Closing.
